# Generated by Django 4.2.7 on 2023-12-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_radanadzorcza'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RadaNadzorcza',
        ),
    ]
