# Generated by Django 4.2.7 on 2023-12-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_kalendarium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pliki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plik', models.FileField(upload_to='pliki/')),
                ('opis', models.CharField(max_length=100)),
            ],
        ),
    ]
