# Generated by Django 4.2.7 on 2023-12-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_aktualnosci'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalendarium',
            name='naglowek',
            field=models.CharField(default='Zapomnialem dodac', max_length=55),
        ),
    ]
